### ISSUE TITLE
[Confusing]What's the point of finding a neighbor node larger than the current one

### ISSUE THREAD

**Issue by Opium1715** [Yiminghh/HiGCN#1]
![image](https://github.com/Yiminghh/HiGCN/assets/90845580/14862867-ade8-465f-ad5e-14330fcfb67f)
Firstly, Excellent work!!! I couldn't understand what the purpose was, and what was the basis for one node being larger than another? Thanks!

**Comment by Yiminghh** [comment]
Thank you for your interest in our work! We only consider neighbors with a larger ID to ensure that we do not count any simplex more than once.

To illustrate this with an example, let's consider the existence of a 2-simplex [v0, v1, v2]. When searching for 2-simplices, this particular simplex would only be identified based on the edge [v0, v1]. While it will not be found based on the edge [v0, v2] or [v1, v2].

**Comment by Opium1715** [comment]
> Thank you for your interest in our work! We only consider neighbors with a larger ID to ensure that we do not count any simplex more than once.
> 
> To illustrate this with an example, let's consider the existence of a 2-simplex [v0, v1, v2]. When searching for 2-simplices, this particular simplex would only be identified based on the edge [v0, v1]. While it will not be found based on the edge [v0, v2] or [v1, v2].
Thank you for your answer, thank you very much.
